# will auto change based on env path we already export.
absolute_path: ''
carla_sh_path: ''

host: 'localhost'
port: 2000
trafficManagerPort: 0
if_open_carla: True # if not pls check the port is correct
record: ''
repetitions: 1
resume: False
checkpoint: None

# Seed used by the TrafficManager (default: 0)
trafficManagerSeed: 0
timeout: 20000
no_rendering: False

# ============== for all route test=============== #
debug: False

# only for debug ===> or just test the agent
routes: 'leaderboard/data/only_one_town.xml'
# towns: ['Town01', 'Town03', 'Town06', 'Town07']
# towns: ['Town02', 'Town04', 'Town05', 'Town10']
# routes: 'leaderboard/data/training_routes/'

scenarios: 'leaderboard/data/all_towns_traffic_scenarios.json'

track: 'MAP' # 'SENSORS'

# ====================== E2E Agent ========================= #
# agent: 'team_code/e2e_agent/mmfn_radar.py'
agent: 'team_code/e2e_agent/mmfn_vectornet.py'
# agent: 'team_code/e2e_agent/mmfn_imgnet.py'
defaults:
  - agent_config: e2e # pls name the model as 'best_model.pth'